# Setup
title:        Intro to RL Reading Group 2022
tagline:      University of Bristol
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       maurock
  url:        

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown